apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustera-prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-operator
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 8.7.0
    helm:
      values: |
{{ include "clustera.prometheus.values" . | indent 8 }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
