apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustera-nginx-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 1.40.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
