apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustera-ns-nginx-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/nginx-ingress
    repoURL: https://github.com/jasonhancock/testing-stuff.git
    targetRevision: HEAD
    helm:
      values: |
        cluster: clustera
        project: default
        server: https://kubernetes.default.svc
        version: 1.40.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
