{{- define "ns-nginx-ingress.values" -}}
# RE: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml
controller:
  kind: DaemonSet
  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
  hostNetwork: true
  nodeSelector:
    node-role.kubernetes.io/ingress: ingress
  metrics:
    enabled: {{ .Values.metrics_enabled }}
    service:
      annotations:
        prometheus.io/scrape: "true"
    serviceMonitor:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: ns
    prometheusRule:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: ns
        app: prometheus-operator
      rules:
        - alert: TooMany500s
          expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            description: Too many 5XXs
            summary: More than 5% of the all requests did return 5XX, this requires your attention
        - alert: TooMany400s
          expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            description: Too many 4XXs
            summary: More than 5% of the all requests did return 4XX, this requires your attention
  config:
    proxy-connect-timeout: "60"
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
    proxy-body-size: "0"
    use-forwarded-headers: "true"
{{- end -}}
