apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-nginx-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.server }}
  project: {{ .Values.project }}
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: {{ .Values.version }}
    helm:
      values: |
{{ include "ns-nginx-ingress.values" . | indent 8 }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
