name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - run: pwd
      - run: sudo apt-get install -y yamllint make
      - run: make lint
