name: tag-release

on:
  push:
    branches:
      - 'master'

jobs:
  tagrelease:
    runs-on: ubuntu-latest
    steps:
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: v0.1.${{ github.run_number }}

